### ISSUE TITLE
Cannot test IE on SauceLabs

### ISSUE THREAD

**Issue by nathagey** [gemini-testing/gemini#174]
I'm getting this error whenever I try to test a IE through SacueLabs.

**Error**
```
✓ type tablet vs fab-h1 plain [internetexplorer11]
Error: [moveTo({"ELEMENT":"0"},0,0)] Error response status: 12, InvalidElementState - An element command could not be completed because the element is in an invalid state (e.g. attempting to click a disabled element). Selenium error: Cannot perform native interaction: Could not load native events component.
Command duration or timeout: 54 milliseconds
Build info: version: '2.18.0', revision: '15704', time: '2012-07-21 01:03:50'
System info: os.name: 'Windows Server 2012 R2', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_45'
Driver info: driver.version: RemoteWebDriver
    at exports.newError (/Users/nhagey/work/commerce/vsdweb/node_modules/gemini/node_modules/wd/lib/utils.js:139:13)
    at /Users/nhagey/work/commerce/vsdweb/node_modules/gemini/node_modules/wd/lib/callbacks.js:33:23
    at /Users/nhagey/work/commerce/vsdweb/node_modules/gemini/node_modules/wd/lib/webdriver.js:174:5
    at Request._callback (/Users/nhagey/work/commerce/vsdweb/node_modules/gemini/node_modules/wd/lib/http-utils.js:87:7)
    at Request.self.callback (/Users/nhagey/work/commerce/vsdweb/node_modules/gemini/node_modules/wd/node_modules/request/request.js:368:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/nhagey/work/commerce/vsdweb/node_modules/gemini/node_modules/wd/node_modules/request/request.js:1219:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/nhagey/work/commerce/vsdweb/node_modules/gemini/node_modules/wd/node_modules/request/request.js:1167:12)
    at IncomingMessage.emit (events.js:117:20)
```

**Test**
```
gemini.suite('h1', function (suite) {
    suite
    	.setUrl('elements/type/guide.html#nav')
        .setCaptureElements('h1')
        .before(function(actions, find) {
            this.button = find('h1');
        })
        .capture('plain');
});

gemini.suite('h2', function (suite) {
    suite
    	.setUrl('elements/type/guide.html#nav')
        .setCaptureElements('h2')
        .before(function(actions, find) {
            this.button = find('h2');
        })
        .capture('plain');
});
```

**gemini.yml**
```
browsers:
  internetexplorer11:
    version: "11.0"
    platform: Windows 8.1

capabilities:
  name: fab-type
  passing: false
  recordVideo: false
  videoUploadOnPass: false
  recordScreenshots: false

windowSize: 1500x880
```

Side note - let me know if you want to pair up on building a [sexy site](https://github.com/gemini-testing/gemini/issues/145). You guys deserve one.

**Comment by arikon** [comment]
> Error: [moveTo({"ELEMENT":"0"},0,0)] Error response status: 12, InvalidElementState - An element command could not be completed because the element is in an invalid state (e.g. attempting to click a disabled element). Selenium error: Cannot perform native interaction: Could not load native events component.

@nathagey This is a error.

Are you sure you are trying to interact with a visible element?

Are you sure the page is loading well?

What is the value of `rootUrl` options you are using?

**Comment by SevInf** [comment]
Closing because no response received. Feel free to reopen if you have any further information.
