### ISSUE TITLE
Generating coverage report always errors

### ISSUE THREAD

**Issue by benedfit** [gemini-testing/gemini#179]
Hi

I get the following error whenever I try to generate a coverage report. I'm using BrowserStack and testing against the latest version of Chrome on Yosemite

```
StateError: Error: Failed to execute 'querySelectorAll' on 'Document': The provided selector is empty.
    at Error (native)
    at Object.exports.all (<anonymous>:250:114)
    at <anonymous>:248:652
    at Array.forEach (native)
    at Object.each (<anonymous>:254:160)
    at coverageForRule (<anonymous>:248:462)
    at Object.exports.collectCoverage (<anonymous>:248:1368)
    at prepareScreenshotUnsafe (<anonymous>:245:478)
    at Object.exports.prepareScreenshot (<anonymous>:245:3113)
    at <anonymous>:240:82
    at /node_modules/gemini/lib/browser/client-bridge.js:42:33
    at _fulfilled (/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/node_modules/gemini/node_modules/q/q.js:796:13)
    at /node_modules/gemini/node_modules/q/q.js:604:44
    at runSingle (/node_modules/gemini/node_modules/q/q.js:137:13)
    at flush (/node_modules/gemini/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:419:13)
```

Anyone had a similar experience?

**Comment by SevInf** [comment]
Hi. Can you provide html page and test so I can look at it?

**Comment by benedfit** [comment]
Sure, my config and tests can be found in the following Gist: https://gist.github.com/benedfit/07cc685b8b14c62f411b

**Comment by SevInf** [comment]
Can you test it on the latest version?

**Comment by benedfit** [comment]
Apologies for the slow reply, but I am still getting this on the latest version

**Comment by benedfit** [comment]
For clarify, this is when using the JavaScript API

**Comment by benedfit** [comment]
I've managed to idenfity that double-colon and @ selectors are causing coverage to fail e.g.:

```
::before

@page

::selection
```

Additionally I have identified that `gemini.coverage.getRules` is returning `null` for one of the stylsheets in `document.styleSheets`. It's not entirely clear why this is happening yet so I will continue to investigate

**Comment by benedfit** [comment]
I'll create new issues and PRs to track these
