### ISSUE TITLE
If an element to be ignored is empty, it causes an error

### ISSUE THREAD

**Issue by varya** [gemini-testing/gemini#192]
I ignore an element like that `suite.ignoreElements('.sg-navigation-section .fa-arrow-left');`

For some reason this element is hidden at one of the pages. It's parrent element has `display: none`. Look here https://img-fotki.yandex.ru/get/15552/14441195.34/0_9336d_6e0ffd63_orig

If running such a test for gathering screenshots, it throws an error:

```
✘ 1.1-1 plain [chrome]
StateError:     at
    at forEach ([native code])
    at
    at
    at
    at
    at
    at La (phantomjs://webpage.evaluate():13:554)
    at phantomjs://webpage.evaluate():13:873
    at phantomjs://webpage.evaluate():13:897
    at phantomjs://webpage.evaluate():14:2
    at global code (phantomjs://webpage.evaluate():14:210)
    at evaluateJavaScript ([native code])
    at
    at _executeCommand (:/ghostdriver/request_handlers/session_request_handler.js:404:90)
    at _handle (:/ghostdriver/request_handlers/session_request_handler.js:142:28)
    at _reroute (:/ghostdriver/request_handlers/request_handler.js:61:20)
    at _handle (:/ghostdriver/request_handlers/router_request_handler.js:78:46)
    at /Users/varya/WebDev/SC5/Elisa/pattern-library/node_modules/gemini/lib/browser/client-bridge.js:42:33
    at _fulfilled (/Users/varya/WebDev/SC5/Elisa/pattern-library/node_modules/gemini/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/varya/WebDev/SC5/Elisa/pattern-library/node_modules/gemini/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/varya/WebDev/SC5/Elisa/pattern-library/node_modules/gemini/node_modules/q/q.js:796:13)
    at /Users/varya/WebDev/SC5/Elisa/pattern-library/node_modules/gemini/node_modules/q/q.js:604:44
    at runSingle (/Users/varya/WebDev/SC5/Elisa/pattern-library/node_modules/gemini/node_modules/q/q.js:137:13)
    at flush (/Users/varya/WebDev/SC5/Elisa/pattern-library/node_modules/gemini/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:442:13)
```

The screenshot of this page is not taken. If selector changes to point out a visible element, everything works OK.

**Comment by arikon** [comment]
@SevInf What do you think? I think it could output warning to the console, but must not crash.

**Comment by SevInf** [comment]
@arikon I agree it should not crash and this is definitely not the expected behaviour. But I don't think the warning is needed. Ignored elements are not as important as capture elements and the same strict rules should not apply to them: it should be ok to silently ignore invisible and absent ignored elements.

**Comment by arikon** [comment]
@SevInf I agree.

**Comment by Dmitriy-kiselyov** [comment]
Does not reproduce
