### ISSUE TITLE
Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by ghost** [gemini-testing/gemini#211]
When run gemini@0.13.0 test command with coverage in config file, program exit with this error:
`
Critical error:
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:116:15)
    at Object.realpathSync (fs.js:1220:18)
    at module.exports.inherit.processRule (C:\inetpub\test_css_373_otladka\node_modules\gemini\lib\coverage.js:200:20)
    at null.<anonymous> (C:\inetpub\test_css_373_otladka\node_modules\gemini\lib\coverage.js:167:26)
    at Array.forEach (native)
    at module.exports.inherit.processRule (C:\inetpub\test_css_373_otladka\node_modules\gemini\lib\coverage.js:166:28)
    at C:\inetpub\test_css_373_otladka\node_modules\gemini\lib\coverage.js:114:27
    at C:\inetpub\test_css_373_otladka\node_modules\gemini\node_modules\q\q.js:1229:26
    at _fulfilled (C:\inetpub\test_css_373_otladka\node_modules\gemini\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\inetpub\test_css_373_otladka\node_modules\gemini\node_modules\q\q.js:863:30)
`

Config file looks like this:
`
rootUrl: http://test-autotest29:173
gridUrl: http://10.76.159.123:4380/wd/hub
screenshotsDir: './screenshots'
windowSize: 1024x768
sessionsPerBrowser: 40
suitesPerSession: 50

browsers:
  chrome:
    desiredCapabilities:
      browserName: chrome

  firefox:
    desiredCapabilities:
      browserName: firefox

system:
  diffColor: '#ff0000'
  coverage:
    enabled: true
    html: true
`

The command to run looks like this:
`
call "%WORKSPACE%\node_modules\.bin\gemini" test tests\online\ --reporter flat --reporter html
`

P.S. With gemini@0.12.7 coverage report created successfully.

**Comment by sipayRT** [comment]
was fixed long time ago
