### ISSUE TITLE
occasional TypeError: Cannot read property 'path' of undefined error in 0.13.0

### ISSUE THREAD

**Issue by elyseholladay** [gemini-testing/gemini#212]
I am now getting the following error on _some_ but not all of my tests, after installing 0.13.0. I did not have this problem w/ 0.12.8. I don't think it's in my tests, as again, some of them run.

Error:

```
$ gemini test --reporter html ./tests/tests/molecules/card.js
Critical error:
TypeError: Cannot read property 'path' of undefined
    at module.exports.inherit._addTestResult (/Users/eholladay/Documents/Projects/roux-ingredients/node_modules/gemini/lib/reporters/html/view-model.js:98:57)
    at module.exports.inherit.addError (/Users/eholladay/Documents/Projects/roux-ingredients/node_modules/gemini/lib/reporters/html/view-model.js:61:14)
    at emit (events.js:129:20)
    at /Users/eholladay/Documents/Projects/roux-ingredients/node_modules/gemini/lib/runner.js:196:31
    at _rejected (/Users/eholladay/Documents/Projects/roux-ingredients/node_modules/gemini/node_modules/q/q.js:844:24)
    at /Users/eholladay/Documents/Projects/roux-ingredients/node_modules/gemini/node_modules/q/q.js:870:30
    at Promise.when (/Users/eholladay/Documents/Projects/roux-ingredients/node_modules/gemini/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/Users/eholladay/Documents/Projects/roux-ingredients/node_modules/gemini/node_modules/q/q.js:788:41)
    at /Users/eholladay/Documents/Projects/roux-ingredients/node_modules/gemini/node_modules/q/q.js:604:44
    at runSingle (/Users/eholladay/Documents/Projects/roux-ingredients/node_modules/gemini/node_modules/q/q.js:137:13)
```

This test runs fine:

```
var gemini = require('gemini');
var windowSizes = require('../window-sizes');

gemini.suite('utilities/showhide', function(parent) {
	parent.setUrl('/inner/utilities')
		.setCaptureElements('#show-hide .ingredient-display')
		.capture('grid-sm', function (actions) {
			actions.setWindowSize(windowSizes.small.height,windowSizes.small.width);
		})
		.capture('grid-med', function (actions) {
			actions.setWindowSize(windowSizes.medium.height,windowSizes.medium.width);
		})
		.capture('grid-lg', function (actions) {
			actions.setWindowSize(windowSizes.large.height,windowSizes.large.width);
		});
});
```

This one fails:

```
var gemini = require('gemini');
var windowSizes = require('../window-sizes');

gemini.suite('molecules/card', function(parent) {
	parent.setUrl('/inner/molecules')
		.setCaptureElements('#card .ingredient-display')
		.capture('grid-sm', function (actions) {
			actions.setWindowSize(windowSizes.small.height,windowSizes.small.width);
		})
		.capture('grid-med', function (actions) {
			actions.setWindowSize(windowSizes.medium.height,windowSizes.medium.width);
		})
		.capture('grid-lg', function (actions) {
			actions.setWindowSize(windowSizes.extralarge.height,windowSizes.extralarge.width);
		});
});
```

You can see they are almost identical except for the element being targeted and the URL. I know that both URLs are up/available.

Also getting this error now:

```
sparkles at roux-ingredients on ROUX-36-refactor   $ gemini test --reporter html ./tests/tests/atoms/buttons.js
Error: ENOENT, open 'gemini-report/index.html'
    at Error (native)
```

Just started running into this problem yesterday :disappointed: Let me know if I can provide any more info/help in any way!

**Comment by elyseholladay** [comment]
maybe also related to #211?

**Comment by sipayRT** [comment]
can't reproduce
