### ISSUE TITLE
npm install issues on Windows 7 64 bit

### ISSUE THREAD

**Issue by benjaminfisher** [gemini-testing/gemini#396]
**When reporting a bug, make sure you provide all required info below. Reports without this information may be closed.**

Output of `gemini --version`:
N/A - Install failed
...

Contents of `.gemini.yml` file:
N/A - Install failed

```yaml

```

Test source code:
N/A - Install failed

```js

```

Command used to run the test:
N/A - Install failed
```
```

Publically accessible URL of the page you are testing against:
N/A - Install failed
http://

Result:

...

Expected behaviour:

...

--------------------------------------------------------------

npm install failed on Windows 7 SP1 64bit

Output log:
```
c:\Users\bfisher1\Documents\development\CasperJs>npm install -g gemini
loadDep:qs → afterAdd     ▀ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"4.4.
loadDep:sntp → request    ▀ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"
loadDep:sntp → resolveWit ▐ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"4.4.0
","npm":"3.5.3"})
WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"4.4.0
","npm":"3.5.3"})
WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"4.4.0
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before w
ill fail on newer node releases. Please update to graceful-fs@^4.0.0 as s
oon as possible.
C:\Users\bfisher1\AppData\Roaming\npm\gemini -> C:\Users\bfisher1\AppData
\Roaming\npm\node_modules\gemini\bin\gemini

> png-img@1.1.4 install C:\Users\bfisher1\AppData\Roaming\npm\node_module
s\gemini\node_modules\png-img
> node-gyp rebuild


C:\Users\bfisher1\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img>if not defined npm_config_node_gyp (node "C:\Users\bfisher1\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Users\bfisher1\AppData\Local\
Programs\Python\Python35\python.EXE" is v3.5.0, which is not supported by
 gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\bfisher1\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:406:14)
gyp ERR! stack     at C:\Users\bfisher1\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:395:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:1
1)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:475:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\bfisher1\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin
\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\bfisher1\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img
gyp ERR! node -v v4.4.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
C:\Users\bfisher1\AppData\Roaming\npm
└── (empty)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\bfisher1\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g
" "gemini"
npm ERR! node v4.4.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! png-img@1.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the png-img@1.1.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the png-img package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs png-img
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls png-img
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\bfisher1\Documents\development\CasperJs\npm-debug.log
npm ERR! code 1
```

**Comment by SwinX** [comment]
@benjaminfisher from log output it seems that installed python version is not compatible with node-gyp. Please see node-gyp [readme](https://github.com/nodejs/node-gyp).

**Comment by benjaminfisher** [comment]
Doesn't seem to work with Python 2.7 either. If I use that switch I end up with a long list of node-gyp issues ending in:
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\n
odejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "gemini" "--python=py
thon2.7"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE

npm ERR! png-img@1.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the png-img@1.1.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the png-img package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project
 with:
npm ERR!     npm bugs png-img
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls png-img
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Rhythm\rhythm-portal\npm-debug.log
```

**Comment by benjaminfisher** [comment]
Just out of curiosity, why is the project still using node-gyp, which hasn't been supported in node since version 0.8?

**Comment by SevInf** [comment]
@benjaminfisher `node-gyp` is current recommended way of doing native modules in node. [See](https://nodejs.org/api/addons.html). Haven't you mistaken it with `node-waf`?

**Comment by SevInf** [comment]
Regarding the issue, I don't think `--python` is `npm` option. The proper way to specify python version is `PYTHON` environment variable set to the full path of python executable

**Comment by sipayRT** [comment]
Closed due to no activity

**Comment by stephenbe** [comment]
```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gemini"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! png-img@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the png-img@2.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the png-img package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs png-img
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls png-img
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projets\Tests\gemini\npm-debug.log

```



@sipayRT I am getting the exact same error as @benjaminfisher ...Anyway I could fix this?

I have c:\python27; in my path...

**Comment by sipayRT** [comment]
sorry, but we don't support windows. But you can try to up your `g++` version

**Comment by stephenbe** [comment]
Is this mentioned in the doc? could have saved me a couple hours knowing you don't support windows

**Comment by sipayRT** [comment]
it not depend on OS but on environment

**Comment by nicrodgers** [comment]
I get the same on MacOSX trying to install the latest code in master:
Failed at the png-img@2.1.0 install script 'node-gyp rebuild'

What do I need to update?

**Comment by sipayRT** [comment]
check your deps pls - https://github.com/nodejs/node-gyp#installation
