### ISSUE TITLE
Cannot screenshot "body" from PhantomJs

### ISSUE THREAD

**Issue by Crash-Man** [gemini-testing/gemini#447]
When using a PhantomJs based setup to capture a full page screenshot, I am encountering the following error:

```
StateError: Failed to capture the element because it is positioned outside of the captured body. Most probably you are trying to capture an absolute positioned element which does not make body height to expand. To fix this place a tall enough <div> on the page to make body expand.
Element position: 0, 0; size: 1366, 2655. Page screenshot size: 1366, 2654. 
    at reportError_ (/home/projects/gemini/node_modules/gemini/lib/capture-session.js:128:27)
    at inherit._cropImage.pageDisposition._validateImage (/home/projects/gemini/node_modules/gemini/lib/capture-session.js:96:20)
    at inherit._cropImage.pageDisposition._validateImage.then [as _cropImage] (/home/projects/gemini/node_modules/gemini/lib/capture-session.js:72:21)
    at null.<anonymous> (/home/projects/gemini/node_modules/gemini/lib/capture-session.js:38:29)
    at _fulfilled (/home/projects/gemini/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/projects/gemini/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/projects/gemini/node_modules/q/q.js:796:13)
    at /home/projects/gemini/node_modules/q/q.js:604:44
    at runSingle (/home/projects/gemini/node_modules/q/q.js:137:13)
    at flush (/home/projects/gemini/node_modules/q/q.js:125:13)
```

Output of `gemini --version`: 4.0.3

`phantomjs -v`: 2.1.1

`gemini-gui -V`" 4.0.0

Contents of `.gemini.yml` file:

```
rootUrl: http://getbootstrap.com
browsers:
  PhantomJS:
    desiredCapabilities:
      browserName: phantomjs
```

Test source code:

```
gemini.suite('page', function (suite) {
  suite.setUrl('/')
    .setCaptureElements('body')
    .capture('plain');
});

```

Command used to run the test:

```
gemini-gui ./test/
```

**Comment by sipayRT** [comment]
hi. Can you provide real page height?

**Comment by sipayRT** [comment]
closed due to inactivity
