### ISSUE TITLE
gemini.suite is not a function 3.0.2 ---> 4.3.0

### ISSUE THREAD

**Issue by vpatton** [gemini-testing/gemini#500]
**When reporting a bug, make sure you provide all required info below. Reports without this information may be closed.**

I upgraded from 3.0.2 to 4.3.0 and now I get this error

TypeError: gemini.suite is not a function
    at Object.<anonymous> (/Users/van.patton/test-framework-gemini/test/spectredemo/VDP.js:3:8)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.exports.requireWithNoCache (/Users/van.patton/test-framework-gemini/node_modules/gemini/lib/utils.js:5:12)
    at /Users/van.patton/test-framework-gemini/node_modules/gemini/lib/test-reader.js:58:15
    at Array.forEach (native)

Output of `gemini --version`:
4.3.0
...

Contents of `.gemini.yml` file:

```yaml
rootUrl: http://
tolerance: 8
screenshotsDir: './screens/phantomjs'
windowSize: 1600x1080
sessionsPerBrowser: 5
suitesPerSession: 10
calibrate: true

browsers:
  PhantomJS:
    desiredCapabilities:
      browserName: 'phantomjs'
      screenResolution: "1280x1024"

system:
  debug: false
```

Test source code:

```js
var gemini = require('gemini');

gemini.suite('Spectre Vehicle Details Page', function(suite){
  suite.setUrl('/new/Acura/2016-Acura-MDX--26d2984b0a0e0ae86dafef0e7ad3585a.htm?_disablePixall=true')
  .before(function( actions, find ){
    actions.wait(5000);
  })
  .ignoreElements('a.home-logolink');

  gemini.suite('Vehicle Details Page Media Viewer Container', function(el){
    el.setCaptureElements('div[data-widget-id="inventory-detail1"]').capture('Media Viewer Widget').ignoreElements('a.home-logolink');
  });

  gemini.suite('Vehicle Details Page Packages & Options Container', function(el){
    el.ignoreElements('a.home-logolink')
    el.setCaptureElements('div[data-widget-name="inventory-detail-packages-options"]').capture('Packages & Options').ignoreElements('a.home-logolink');
  });

  gemini.suite('Vehicle Details Page Item Details', function(el){
    el.ignoreElements('a.home-logolink')
    el.setCaptureElements('div[data-widget-id="inventory-item-details2"]').capture('Vehicle Specs').ignoreElements('a.home-logolink');
  });

  gemini.suite('Vehicle Details Page Quick Specs Container', function(el){
    el.ignoreElements('a.home-logolink') 
    el.setCaptureElements('div[data-widget-name="inventory-detail-quick-specs"]').capture('Quick Specs').ignoreElements('a.home-logolink');
  });

  gemini.suite('Vehicle Details Page Detailed Pricing Container', function(el){
    el.ignoreElements('a.home-logolink')
    el.setCaptureElements('div[data-widget-id="inventory-detail2"]').capture('Payment Calculator').ignoreElements('a.home-logolink');
  });

  gemini.suite('Vehicle Details Page Share Container', function(el){
    el.ignoreElements('a.home-logolink')
    el.setCaptureElements('div[data-widget-id="links5"]').capture('Share Buttons').ignoreElements('a.home-logolink');
  });

  gemini.suite('Vehicle Details Page Tech Specs', function(el){
    el.ignoreElements('a.home-logolink')
    el.setCaptureElements('div[data-widget-id="inventory-detail5"]').capture('Tech Specs').ignoreElements('a.home-logolink');
  });
  
});
```

Command used to run the test:

```
gemini update test/spectredemo -c phantom.yml
```
```
Result:
TypeError: gemini.suite is not a function
    at Object.<anonymous> (/Users/van.patton/test-framework-gemini/test/spectredemo/VDP.js:3:8)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.exports.requireWithNoCache (/Users/van.patton/test-framework-gemini/node_modules/gemini/lib/utils.js:5:12)
    at /Users/van.patton/test-framework-gemini/node_modules/gemini/lib/test-reader.js:58:15
    at Array.forEach (native)
```

Expected behaviour:

...

**Comment by vpatton** [comment]
update, I uninstalled & reinstalled gemini globally and created a new directory and used the example tests you have on the main page 
var gemini = require('gemini');
 
gemini.suite('yandex-search', function(suite) {
    suite.setUrl('/')
        .setCaptureElements('.main-table')
        .capture('plain')
        .capture('with text', function(actions, find) {
            actions.sendKeys(find('.input__control'), 'hello gemini');
        });
});

still get the same error as above

**Comment by eGavr** [comment]
remove `var gemini = require('gemini')` from your test file and everything will be ok.

The doc will be fixed soon.

**Comment by sipayRT** [comment]
@vpatton you can use actual doc from github.
