### ISSUE TITLE
"Cannot find files by mask gemini"

### ISSUE THREAD

**Issue by niedzielski** [gemini-testing/gemini#569]
Output of `gemini --version`: 4.7.2
Output of `node -v`: v6.4.0

Contents of `.gemini.yml` file:

```yaml
rootUrl: http://localhost:8080
browsers:
  phantomjs:
    gridUrl: http://localhost:8910
    desiredCapabilities:
      browserName: phantomjs
```

Test source code:

```js
const phantom = require('phantomjs')

const viewports = [{w: 160, h: 144}, {w: 320, h: 240}, {w: 480, h: 320},
  {w: 640, h: 480}]

gemini.suite('zzz-card', function(suite) {
  suite
    .setUrl('/test/screenshot/fixture/zzz-card.html')
    .setCaptureElements('body')
    .before(function(actions, find) {
      actions.wait(1000)
    })
  viewports.forEach(function(viewport) {
    suite
      .capture('zzz-card-' + viewport.w + 'x' + viewport.h, function(actions, find) {
        actions.setWindowSize(viewport.w, viewport.h)
      })
  })
})
```

Command used to run the test:

Setup:
```bash
http-server -c-1&
phantomjs -w&
```

Run tests from command line:
```bash
gemini test foo.js
```

Run tests from GUI:
```bash
gemini-gui foo.js
```

Command line result:
```
Critical error:
Error: Cannot find files by mask gemini
    at q.nfcall.then (/home/stephen/dev/js/lizzzt/lizzztlib/node_modules/glob-extra/lib/index.js:14:28)
    at _fulfilled (/home/stephen/dev/js/lizzzt/lizzztlib/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/stephen/dev/js/lizzzt/lizzztlib/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/stephen/dev/js/lizzzt/lizzztlib/node_modules/q/q.js:796:13)
    at /home/stephen/dev/js/lizzzt/lizzztlib/node_modules/q/q.js:604:44
    at runSingle (/home/stephen/dev/js/lizzzt/lizzztlib/node_modules/q/q.js:137:13)
    at flush (/home/stephen/dev/js/lizzzt/lizzztlib/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

GUI result:
```
/home/stephen/.node/lib/node_modules
/home/stephen/dev/js/lizzzt/lizzztlib/node_modules/q/q.js:155
                throw e;
                ^

Error: Cannot find files by mask gemini
    at q.nfcall.then (/home/stephen/dev/js/lizzzt/lizzztlib/node_modules/glob-extra/lib/index.js:14:28)
    at _fulfilled (/home/stephen/dev/js/lizzzt/lizzztlib/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/stephen/dev/js/lizzzt/lizzztlib/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/stephen/dev/js/lizzzt/lizzztlib/node_modules/q/q.js:796:13)
    at /home/stephen/dev/js/lizzzt/lizzztlib/node_modules/q/q.js:604:44
    at runSingle (/home/stephen/dev/js/lizzzt/lizzztlib/node_modules/q/q.js:137:13)
    at flush (/home/stephen/dev/js/lizzzt/lizzztlib/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Expected behaviour:
This worked properly in v4.4.1 but doesn't in v4.7.2.

**Comment by sipayRT** [comment]
hi. Can you check it in v4.8.0?

**Comment by niedzielski** [comment]
Yay!! It works! :+1:
