### ISSUE TITLE
Show errors in case of incorrect path to test suite

### ISSUE THREAD

**Issue by enotramone** [gemini-testing/gemini#58]
I store my tests in a non-root directory and don’t want to write a full path to it. So, I created a symbolic link to my tests in the root folder and run tests with simple command like: `gemini test folder_with_tests/test.js`

I didn’t get any errors, but non of tests passed:

```
$ gemini test /symlink_folder/test.js
Total: 0 Passed: 0 Failed: 0 Skipped: 0
```

In case without opening slash:

```
$ gemini test symlink_folder/test.js
Error: Cannot find module 'gemini'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (absolute/path/to/suite/test.js:1:76)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Also noted that in case of given a totally wrong path — there is no any error messages:

```
$ gemini gather any_folder_name/any_file_name.some_extension
Total: 0 Passed: 0 Failed: 0 Skipped: 0
```
##

**Comment by Dmitriy-kiselyov** [comment]
Does not reproduce
