### ISSUE TITLE
Error: options.reporter is undefined while updating screenshots

### ISSUE THREAD

**Issue by frux** [gemini-testing/gemini#711]
Output of `gemini --version`: 4.15.0

Command used to run the test:

```
gemini update --root-url=https://example.com
```

Result:
```
Critical error:
TypeError: Cannot read property 'map' of undefined
    at parseReporterOptions (/Users/frux/myproject/node_modules/gemini/lib/cli/index.js:101:40)
    at Promise.try.then (/Users/frux/myproject/node_modules/gemini/lib/cli/index.js:110:28)
    at tryCatcher (/Users/frux/myproject/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/frux/myproject/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/frux/myproject/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/Users/frux/myproject/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/Users/frux/myproject/node_modules/bluebird/js/release/async.js:143:12)(/Users/frux/myproject/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/frux/myproject/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by frux** [comment]
Reinstallation of node_modules fixed it
