### ISSUE TITLE
waitForElementToHide not working as expected

### ISSUE THREAD

**Issue by frederikmartin** [gemini-testing/gemini#727]
Output of `gemini --version`:

4.16.0

Contents of `.gemini.js` file:

```javascript
module.exports = {
    rootUrl: 'http://localhost:1337/#',
    gridUrl: 'http://localhost:4444/wd/hub',
    windowSize: '1600x1080',
    screenshotMode: 'fullpage',
    compositeImage: true,
    sessionsPerBrowser: 1,
    browsers: {
        chrome: {
            desiredCapabilities: {
                browserName: 'chrome'
            }
        }
    },
    system: {
        sourceRoot: './src',
        coverage: {
            enabled: false
        }
    }
};
```

Test source code:

```javascript
gemini.suite('account', function (suite) {
    gemini.suite('reset password request', function (suite) {
        suite.setUrl('/')
            .setCaptureElements('md-dialog.container__dialog--password-reset')
            .capture('reset password dialog', function (actions, find) {
                actions.click(find('[ng-click="LoginCtrl.showResetPassword()"]'));
                actions.waitForElementToShow('md-dialog.container__dialog--password-reset', 5000);
            })
            .capture('close dialog with button', function (actions, find) {
                actions.click('[ng-click="ResetPasswordCtrl.cancel()"]');
                // Wait for dialog to close
                actions.waitForElementToHide('md-dialog.container__dialog--password-reset', 15000);
            });
    });
});
```

Command used to run the test:

```
gemini test --reporter flat --reporter html
```

Expected behaviour:

Dialog should be closed, but instead there is an error returned:

```
StateError: Area with css selector : md-dialog.container__dialog--password-reset is hidden
    at /usr/local/lib/node_modules/gemini/lib/browser/client-bridge.js:42:39
    at tryCatcher (/usr/local/lib/node_modules/gemini/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/gemini/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/gemini/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/gemini/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/gemini/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/usr/local/lib/node_modules/gemini/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/gemini/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/gemini/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by frederikmartin** [comment]
Sorry, this was a layer 8 problem. I set the dialog as element to capture which I then close. So it was not the `waitForElementToHide` which caused the error, but the `capture`. My bad.
