### ISSUE TITLE
Error install gemini on Ubuntu

### ISSUE THREAD

**Issue by Drm1804** [gemini-testing/gemini#817]
I have the problem with installation gemini of global on Ubuntu 16.04
I run `sudo npm install -g gemini`

And have error :+1: 
`
/usr/local/bin/gemini -> /usr/local/lib/node_modules/gemini/bin/gemini

> png-img@2.1.1 install /usr/local/lib/node_modules/gemini/node_modules/png-img
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/gemini/node_modules/png-img/build'
gyp ERR! System Linux 4.10.0-33-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/gemini/node_modules/png-img
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! png-img@2.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the png-img@2.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/austinov/.npm/_logs/2017-09-08T16_07_35_740Z-debug.log

`

**Comment by sipayRT** [comment]
why did you install `gemini` with sudo? try to reinstall it without `sudo` - it should help

**Comment by j0tunn** [comment]
@Drm1804 take a look at [this guide](https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md)

**Comment by Electr0n** [comment]
I had same issue.
The solution is to install gemini without sudo. Node-gyp is sensetive to permisions. Just change permisions to your node_modules folder and install it without sudo.

**Comment by mikhail-putilov** [comment]
Reproducible. 
```
─snowy@misha-Precision-Tower-3620 ~ 
╰─$ npm install -g gemini

/home/snowy/.npm-global/bin/gemini -> /home/snowy/.npm-global/lib/node_modules/gemini/bin/gemini

> png-img@2.2.0 install /home/snowy/.npm-global/lib/node_modules/gemini/node_modules/png-img
> node-gyp rebuild

make: Entering directory '/home/snowy/.npm-global/lib/node_modules/gemini/node_modules/png-img/build'
  CC(target) Release/obj.target/libpng/third_party/libpng/png.o
In file included from ../third_party/libpng/png.c:14:0:
../third_party/libpng/pngpriv.h:44:12: fatal error: stdlib.h: No such file or directory
 #  include <stdlib.h>
            ^~~~~~~~~~
compilation terminated.
third_party/libpng/libpng.target.mk:116: recipe for target 'Release/obj.target/libpng/third_party/libpng/png.o' failed
make: *** [Release/obj.target/libpng/third_party/libpng/png.o] Error 1
make: Leaving directory '/home/snowy/.npm-global/lib/node_modules/gemini/node_modules/png-img/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.15.0-50-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/snowy/.npm-global/lib/node_modules/gemini/node_modules/png-img
gyp ERR! node -v v11.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! png-img@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the png-img@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/snowy/.npm/_logs/2019-05-24T08_00_42_898Z-debug.log
```

**Comment by j0tunn** [comment]
@mikhail-putilov you should install some deps. Try `$ sudo apt-get install build-essential`

**Comment by Qbes179** [comment]
CC(target) Release/obj.target/zlib/third_party/zlib/inffast.o
  CC(target) Release/obj.target/zlib/third_party/zlib/inflate.o
../third_party/zlib/inflate.c: In function ‘inflateMark’:
../third_party/zlib/inflate.c:1507:61: warning: left shift of negative value [-Wshift-negative-value]
  == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                 ^~
../third_party/zlib/inflate.c: In function ‘inflate’:
../third_party/zlib/inflate.c:720:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = EXLEN;
             ~~~~~~~~~~~~^~~~~~~
../third_party/zlib/inflate.c:721:9: note: here
         case EXLEN:
         ^~~~
../third_party/zlib/inflate.c:732:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = EXTRA;
             ~~~~~~~~~~~~^~~~~~~
../third_party/zlib/inflate.c:733:9: note: here
         case EXTRA:
         ^~~~
../third_party/zlib/inflate.c:754:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = NAME;
             ~~~~~~~~~~~~^~~~~~
../third_party/zlib/inflate.c:755:9: note: here
         case NAME:
         ^~~~
../third_party/zlib/inflate.c:775:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = COMMENT;
             ~~~~~~~~~~~~^~~~~~~~~
../third_party/zlib/inflate.c:776:9: note: here
         case COMMENT:
         ^~~~
../third_party/zlib/inflate.c:795:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = HCRC;
             ~~~~~~~~~~~~^~~~~~
../third_party/zlib/inflate.c:796:9: note: here
         case HCRC:
         ^~~~
../third_party/zlib/inflate.c:818:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = DICT;
             ~~~~~~~~~~~~^~~~~~
../third_party/zlib/inflate.c:819:9: note: here
         case DICT:
         ^~~~
../third_party/zlib/inflate.c:825:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = TYPE;
             ~~~~~~~~~~~~^~~~~~
../third_party/zlib/inflate.c:826:9: note: here
         case TYPE:
         ^~~~
../third_party/zlib/inflate.c:827:16: warning: this statement may fall through [-Wimplicit-fallthrough=]
             if (flush == Z_BLOCK || flush == Z_TREES) goto inf_leave;
                ^
../third_party/zlib/inflate.c:828:9: note: here
         case TYPEDO:
         ^~~~
../third_party/zlib/inflate.c:877:16: warning: this statement may fall through [-Wimplicit-fallthrough=]
             if (flush == Z_TREES) goto inf_leave;
                ^
../third_party/zlib/inflate.c:878:9: note: here
         case COPY_:
         ^~~~
../third_party/zlib/inflate.c:879:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = COPY;
             ~~~~~~~~~~~~^~~~~~
../third_party/zlib/inflate.c:880:9: note: here
         case COPY:
         ^~~~
../third_party/zlib/inflate.c:1018:16: warning: this statement may fall through [-Wimplicit-fallthrough=]
             if (flush == Z_TREES) goto inf_leave;
                ^
../third_party/zlib/inflate.c:1019:9: note: here
         case LEN_:
         ^~~~
../third_party/zlib/inflate.c:1020:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = LEN;
             ~~~~~~~~~~~~^~~~~
../third_party/zlib/inflate.c:1021:9: note: here
         case LEN:
         ^~~~
../third_party/zlib/inflate.c:1069:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = LENEXT;
             ~~~~~~~~~~~~^~~~~~~~
../third_party/zlib/inflate.c:1070:9: note: here
         case LENEXT:
         ^~~~
../third_party/zlib/inflate.c:1079:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = DIST;
             ~~~~~~~~~~~~^~~~~~
../third_party/zlib/inflate.c:1080:9: note: here
         case DIST:
         ^~~~
../third_party/zlib/inflate.c:1106:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = DISTEXT;
             ~~~~~~~~~~~~^~~~~~~~~
../third_party/zlib/inflate.c:1107:9: note: here
         case DISTEXT:
         ^~~~
../third_party/zlib/inflate.c:1122:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = MATCH;
             ~~~~~~~~~~~~^~~~~~~
../third_party/zlib/inflate.c:1123:9: note: here
         case MATCH:
         ^~~~
../third_party/zlib/inflate.c:1197:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = LENGTH;
             ~~~~~~~~~~~~^~~~~~~~
../third_party/zlib/inflate.c:1198:9: note: here
         case LENGTH:
         ^~~~
../third_party/zlib/inflate.c:1210:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = DONE;
             ~~~~~~~~~~~~^~~~~~
../third_party/zlib/inflate.c:1211:9: note: here
         case DONE:
         ^~~~
  CC(target) Release/obj.target/zlib/third_party/zlib/inftrees.o
  CC(target) Release/obj.target/zlib/third_party/zlib/trees.o
  CC(target) Release/obj.target/zlib/third_party/zlib/uncompr.o
  CC(target) Release/obj.target/zlib/third_party/zlib/zutil.o
  AR(target) Release/obj.target/third_party/zlib/zlib.a
  COPY Release/zlib.a
  CXX(target) Release/obj.target/png_img/src/init.o
  CXX(target) Release/obj.target/png_img/src/PngImgAdapter.o
../src/PngImgAdapter.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE PngImgAdapter::Get(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/PngImgAdapter.cc:87:46: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   auto pPxl = img.Get(info[0]->Uint32Value(), info[1]->Uint32Value());
                                            ^
In file included from /tmp/.node-gyp/10.15.3/include/node/v8.h:26:0,
                 from /tmp/.node-gyp/10.15.3/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/./PngImgAdapter.h:4,
                 from ../src/PngImgAdapter.cc:1:
/tmp/.node-gyp/10.15.3/include/node/v8.h:2477:47: note: declared here
 8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                            ^
/tmp/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/PngImgAdapter.cc:87:70: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
 g.Get(info[0]->Uint32Value(), info[1]->Uint32Value());
                                                    ^
In file included from /tmp/.node-gyp/10.15.3/include/node/v8.h:26:0,
                 from /tmp/.node-gyp/10.15.3/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/./PngImgAdapter.h:4,
                 from ../src/PngImgAdapter.cc:1:
/tmp/.node-gyp/10.15.3/include/node/v8.h:2477:47: note: declared here
 8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                            ^
/tmp/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/PngImgAdapter.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE PngImgAdapter::Fill(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/PngImgAdapter.cc:120:30: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         info[0]->Uint32Value(),
                              ^
In file included from /tmp/.node-gyp/10.15.3/include/node/v8.h:26:0,
                 from /tmp/.node-gyp/10.15.3/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/./PngImgAdapter.h:4,
                 from ../src/PngImgAdapter.cc:1:
/tmp/.node-gyp/10.15.3/include/node/v8.h:2477:47: note: declared here
 8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                            ^
/tmp/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/PngImgAdapter.cc:121:30: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         info[1]->Uint32Value(),
                              ^
In file included from /tmp/.node-gyp/10.15.3/include/node/v8.h:26:0,
                 from /tmp/.node-gyp/10.15.3/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/./PngImgAdapter.h:4,
                 from ../src/PngImgAdapter.cc:1:
/tmp/.node-gyp/10.15.3/include/node/v8.h:2477:47: note: declared here
 8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                            ^
/tmp/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/PngImgAdapter.cc:122:30: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         info[2]->Uint32Value(),
                              ^
In file included from /tmp/.node-gyp/10.15.3/include/node/v8.h:26:0,
                 from /tmp/.node-gyp/10.15.3/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/./PngImgAdapter.h:4,
                 from ../src/PngImgAdapter.cc:1:
/tmp/.node-gyp/10.15.3/include/node/v8.h:2477:47: note: declared here
 8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                            ^
/tmp/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/PngImgAdapter.cc:123:30: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         info[3]->Uint32Value(),
                              ^
In file included from /tmp/.node-gyp/10.15.3/include/node/v8.h:26:0,
                 from /tmp/.node-gyp/10.15.3/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/./PngImgAdapter.h:4,
                 from ../src/PngImgAdapter.cc:1:
/tmp/.node-gyp/10.15.3/include/node/v8.h:2477:47: note: declared here
 8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                            ^
/tmp/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/PngImgAdapter.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE PngImgAdapter::Crop(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/PngImgAdapter.cc:137:30: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         info[0]->Uint32Value(),
                              ^
In file included from /tmp/.node-gyp/10.15.3/include/node/v8.h:26:0,
                 from /tmp/.node-gyp/10.15.3/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/./PngImgAdapter.h:4,
                 from ../src/PngImgAdapter.cc:1:
/tmp/.node-gyp/10.15.3/include/node/v8.h:2477:47: note: declared here
 8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                            ^
/tmp/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/PngImgAdapter.cc:138:30: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         info[1]->Uint32Value(),
                              ^
In file included from /tmp/.node-gyp/10.15.3/include/node/v8.h:26:0,
                 from /tmp/.node-gyp/10.15.3/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/./PngImgAdapter.h:4,
                 from ../src/PngImgAdapter.cc:1:
/tmp/.node-gyp/10.15.3/include/node/v8.h:2477:47: note: declared here
 8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                            ^
/tmp/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/PngImgAdapter.cc:139:30: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         info[2]->Uint32Value(),
                              ^
In file included from /tmp/.node-gyp/10.15.3/include/node/v8.h:26:0,
                 from /tmp/.node-gyp/10.15.3/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/./PngImgAdapter.h:4,
                 from ../src/PngImgAdapter.cc:1:
/tmp/.node-gyp/10.15.3/include/node/v8.h:2477:47: note: declared here
 8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                            ^
/tmp/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/PngImgAdapter.cc:140:30: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         info[3]->Uint32Value()
                              ^
In file included from /tmp/.node-gyp/10.15.3/include/node/v8.h:26:0,
                 from /tmp/.node-gyp/10.15.3/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/./PngImgAdapter.h:4,
                 from ../src/PngImgAdapter.cc:1:
/tmp/.node-gyp/10.15.3/include/node/v8.h:2477:47: note: declared here
 8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                            ^
/tmp/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/PngImgAdapter.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE PngImgAdapter::SetSize(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/PngImgAdapter.cc:153:30: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         info[0]->Uint32Value(),
                              ^
In file included from /tmp/.node-gyp/10.15.3/include/node/v8.h:26:0,
                 from /tmp/.node-gyp/10.15.3/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/./PngImgAdapter.h:4,
                 from ../src/PngImgAdapter.cc:1:
/tmp/.node-gyp/10.15.3/include/node/v8.h:2477:47: note: declared here
 8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                            ^
/tmp/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/PngImgAdapter.cc:154:30: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         info[1]->Uint32Value()
                              ^
In file included from /tmp/.node-gyp/10.15.3/include/node/v8.h:26:0,
                 from /tmp/.node-gyp/10.15.3/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/./PngImgAdapter.h:4,
                 from ../src/PngImgAdapter.cc:1:
/tmp/.node-gyp/10.15.3/include/node/v8.h:2477:47: note: declared here
 8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                            ^
/tmp/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/PngImgAdapter.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE PngImgAdapter::Insert(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/PngImgAdapter.cc:164:67: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
 rap::Unwrap<PngImgAdapter>(info[0]->ToObject())->img_,
                                              ^
In file included from /tmp/.node-gyp/10.15.3/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/./PngImgAdapter.h:4,
                 from ../src/PngImgAdapter.cc:1:
/tmp/.node-gyp/10.15.3/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
../src/PngImgAdapter.cc:165:30: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         info[1]->Uint32Value(),
                              ^
In file included from /tmp/.node-gyp/10.15.3/include/node/v8.h:26:0,
                 from /tmp/.node-gyp/10.15.3/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/./PngImgAdapter.h:4,
                 from ../src/PngImgAdapter.cc:1:
/tmp/.node-gyp/10.15.3/include/node/v8.h:2477:47: note: declared here
 8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                            ^
/tmp/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/PngImgAdapter.cc:166:30: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         info[2]->Uint32Value()
                              ^
In file included from /tmp/.node-gyp/10.15.3/include/node/v8.h:26:0,
                 from /tmp/.node-gyp/10.15.3/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/./PngImgAdapter.h:4,
                 from ../src/PngImgAdapter.cc:1:
/tmp/.node-gyp/10.15.3/include/node/v8.h:2477:47: note: declared here
 8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                            ^
/tmp/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  CXX(target) Release/obj.target/png_img/src/PngImg.o
  SOLINK_MODULE(target) Release/obj.target/png_img.node
  COPY Release/png_img.node
make: выход из каталога «/home/qbes/poligon/oneshot/node_modules/png-img/build»
+ gemini@7.4.1
added 421 packages from 386 contributors and audited 2442 packages in 22.594s
found 5 vulnerabilities (3 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by Qbes179** [comment]
qbes@qbes-pc:~/poligon/oneshot$ npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.0.14 <4.1.0 || >=4.1.2                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gemini                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gemini > gemini-coverage > handlebars                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/755                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Cross-Site Scripting                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.0.0                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gemini                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gemini > gemini-coverage > handlebars                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/61                              │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ braces                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.3.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gemini                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gemini > micromatch > braces                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/786                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Incorrect Handling of Non-Boolean Comparisons During         │
│               │ Minification                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ uglify-js                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 2.4.24                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gemini                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gemini > gemini-coverage > handlebars > uglify-js            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/39                              │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ uglify-js                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.6.0                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gemini                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gemini > gemini-coverage > handlebars > uglify-js            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/48                              │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 5 vulnerabilities (3 low, 2 high) in 2443 scanned packages
  5 vulnerabilities require manual review. See the full report for details.
