### ISSUE TITLE
Unable to run tests on IE11 with selenium standalone

### ISSUE THREAD

**Issue by vinayakpatil** [gemini-testing/gemini#818]
**When reporting a bug, make sure you provide all required info below. Reports without this information may be closed.**

Error: [moveTo({"element-6066-11e4-a52e-4f735466cecf":"18d58b9a-dd8f-41b2-9c74-844a97add558"},0,0)] Error response status: 9, UnknownCommand - The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource. Selenium error: mouseMoveTo
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:54:15.039Z'
System info: host: 'IND-VIPATIL', ip: '192.168.56.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_25'
Driver info: driver.version: unknown
    at exports.newError (C:\Users\vipatil\AppData\Roaming\nvm\v6.9.1\node_modules\gemini\node_modules\wd\lib\utils.js:139:13)
    at C:\Users\vipatil\AppData\Roaming\nvm\v6.9.1\node_modules\gemini\node_modules\wd\lib\callbacks.js:33:23
    at C:\Users\vipatil\AppData\Roaming\nvm\v6.9.1\node_modules\gemini\node_modules\wd\lib\webdriver.js:174:5
    at Request._callback (C:\Users\vipatil\AppData\Roaming\nvm\v6.9.1\node_modules\gemini\node_modules\wd\lib\http-utils.js:87:7)
    at Request.self.callback (C:\Users\vipatil\AppData\Roaming\nvm\v6.9.1\node_modules\gemini\node_modules\request\request.js:368:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\vipatil\AppData\Roaming\nvm\v6.9.1\node_modules\gemini\node_modules\request\request.js:1219:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\vipatil\AppData\Roaming\nvm\v6.9.1\node_modules\gemini\node_modules\request\request.js:1167:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Output of `gemini --version`: 5.0.0-alpha.8

...

Contents of `.gemini.yml` file:
 
```json

const config = {
  "rootUrl": `http://${ip.address()}:4200/`,
  "gridUrl": "http://127.0.0.1:4444/wd/hub",
  "compositeImage": true,
  "tolerance": 3.5,
  "windowSize": "1600x2400",

  "httpTimeout": 60000,
  "retry": 2,

  "browsers": {
    "internet explorer": {
      "desiredCapabilities": {
        "browserName": "internet explorer",
        "version": "10"
      }
    }
  },
  "system": {
    "plugins": {
      "html-reporter": {
        "enabled": true
      }
    }
  }
};

```

Test source code:

```js

```

Command used to run the test:

```
```

Publically accessible URL of the page you are testing against:

http://localhost:4200

Result:

...

Expected behaviour:

Should be able to run tests on IE11

**Comment by ibolmo** [comment]
Same here.

**Comment by nikita9** [comment]
@vinayakpatil @ibolmo There is possible solution of this issue to use another version of selenium. 

**Here is:** 

- `selenium-standalone install --version=2.47.0 --drivers.ie.version=2.53.1`
- `selenium-standalone start --version=2.47.0 --drivers.ie.version=2.53.1`
