### ISSUE TITLE
IE11 - Error: no value passed to Element constructor

### ISSUE THREAD

**Issue by StasGrishaev** [gemini-testing/gemini#860]
приветствую, столкнулся с проблемой при попытке снять скриншоты в IE11 - стек прилагается. 
что пробовал : 

- переустанавливать webdriver-manager из npm
- использовать 64 или 32 битные версии IEdriverServer
- пробовал standalone selenium server

на этом попытки закончились.
версия IE11 - 11.0.49
версия IE драйвера - 3.8.0

на всякий случай стек SeleniumServer

`02:02:03.957 INFO - /session: Executing POST on /session (handler: BeginSession)
02:02:04.012 INFO - Capabilities are: Capabilities {browserName: internet explorer, javascriptEnabled: true, version: 11}
02:02:04.012 INFO - Capabilities {browserName: internet explorer, javascriptEnabled: true, version: 11} matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.ie.InternetExplorerDriverService)
Started InternetExplorerDriver server (32-bit)
3.8.0.0
Listening on port 40726
Only local connections are allowed
02:02:08.672 INFO - Detected dialect: W3C
02:02:08.706 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@c45e3f
02:02:08.707 INFO - Handler thread for session b0d3f8c3-4214-47d2-8967-925c756c03f9 (internet explorer): Executing POST on /session/b0d3f8c3-4214-47d2-8967-925c756c03f9/window/current/size (handler: ServicedSession)
02:02:09.022 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@c45e3f
02:02:09.023 INFO - Handler thread for session b0d3f8c3-4214-47d2-8967-925c756c03f9 (internet explorer): Executing POST on /session/b0d3f8c3-4214-47d2-8967-925c756c03f9/execute (handler: ServicedSession)
02:02:09.075 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@c45e3f
02:02:09.076 INFO - Handler thread for session b0d3f8c3-4214-47d2-8967-925c756c03f9 (internet explorer): Executing POST on /session/b0d3f8c3-4214-47d2-8967-925c756c03f9/moveto (handler: ServicedSession)
02:02:09.095 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@c45e3f
02:02:09.096 INFO - Handler thread for session b0d3f8c3-4214-47d2-8967-925c756c03f9 (internet explorer): Executing POST on /session/b0d3f8c3-4214-47d2-8967-925c756c03f9/url (handler: ServicedSession)
02:02:09.362 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@c45e3f
02:02:09.362 INFO - Handler thread for session b0d3f8c3-4214-47d2-8967-925c756c03f9 (internet explorer): Executing POST on /session/b0d3f8c3-4214-47d2-8967-925c756c03f9/execute (handler: ServicedSession)
02:02:09.406 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@c45e3f
02:02:09.407 INFO - Handler thread for session b0d3f8c3-4214-47d2-8967-925c756c03f9 (internet explorer): Executing POST on /session/b0d3f8c3-4214-47d2-8967-925c756c03f9/execute (handler: ServicedSession)
02:02:09.629 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@c45e3f
02:02:09.630 INFO - Handler thread for session b0d3f8c3-4214-47d2-8967-925c756c03f9 (internet explorer): Executing POST on /session/b0d3f8c3-4214-47d2-8967-925c756c03f9/execute (handler: ServicedSession)
02:02:09.761 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@c45e3f
02:02:09.762 INFO - Handler thread for session b0d3f8c3-4214-47d2-8967-925c756c03f9 (internet explorer): Executing POST on /session/b0d3f8c3-4214-47d2-8967-925c756c03f9/elements (handler: ServicedSession)`

Output of `gemini --version`:

5.0.0-alpha.10

Contents of `.gemini.js` file:

```
module.exports = {
    rootUrl: 'http://localhost:9000',
    gridUrl: 'http://127.0.0.1:4444/wd/hub',
    compositeImage: true,
    sessionsPerBrowser: 1,
    calibrate: false,

    browsers: {
        // chrome: {
        //     screenshotsDir: './screens/chrome',
        //     windowSize: '1920x1080',
        //     desiredCapabilities: {
        //         browserName: 'chrome'
        //     }
        // },
        // firefox:{
        //     windowSize: '1920x1080',
        //     screenshotsDir: './screens/ff',
        //     desiredCapabilities:{
        //         browserName: 'firefox',
        //         marionette: false
        //     }
        // },
        // edge:{
        // 	windowSize: '1920x1080',
        //     screenshotsDir: './screens/edge',
        //     desiredCapabilities:{
        //         browserName: 'MicrosoftEdge'
        //     }
        // },
        ie:{
            windowSize: '1920x1080',
            screenshotsDir: './gemini/ie-screens',
            desiredCapabilities:{
                browserName: 'internet explorer',
                version: '11'
            }
        }
    },

    sets:{
    	chrome:{
    		files:"C:/Users/User/Documents/project/__test__/css_regression/tests"
    	},
    	// firefox:{
    	// 	files:"C:/Users/User/Documents/project/__test__/css_regression"
    	// },
    }
};
```

Test source code:

```js
gemini.suite( "overview", function( suite ) {

	/**
	 *  Suite: Check of Login page
	 */
	suite.setUrl( "/#/members/11095" )
	     .before( function( actions ) {
		     actions.waitForElementToShow( ".ldv-header", 45000 );
		     actions.wait(5000);
	     } )
	     .setCaptureElements( [
		     ".memberView"
	     ] )
	     .ignoreElements('.ldv-content-section', {every: '.ldv-service-number-tooltip.ng-scope'})
	     .capture("plain");
} );
```

Command used to run the test:

```
gemini-gui
```

Result:

`(node:1816) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Critical error:
Error: no value passed to Element constructor
    at PromiseElement.Element (C:\Users\User\Documents\mentrics\ODHWeb\FrontEndApp\node_modules\wd\lib\element.js:15:11)
    at new PromiseElement (C:\Users\User\Documents\mentrics\ODHWeb\FrontEndApp\node_modules\wd\lib\promise-webdriver.js:73:20)
    at PromiseWebdriver.newElement (C:\Users\User\Documents\mentrics\ODHWeb\FrontEndApp\node_modules\wd\lib\promise-webdriver.js:103:12)
    at C:\Users\User\Documents\mentrics\ODHWeb\FrontEndApp\node_modules\wd\lib\callbacks.js:137:24
    at C:\Users\User\Documents\mentrics\ODHWeb\FrontEndApp\node_modules\wd\lib\callbacks.js:82:7
    at C:\Users\User\Documents\mentrics\ODHWeb\FrontEndApp\node_modules\wd\lib\webdriver.js:174:5
    at Request._callback (C:\Users\User\Documents\mentrics\ODHWeb\FrontEndApp\node_modules\wd\lib\http-utils.js:87:7)
    at Request.self.callback (C:\Users\User\Documents\mentrics\ODHWeb\FrontEndApp\node_modules\wd\node_modules\request\request.js:368:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (C:\Users\User\Documents\mentrics\ODHWeb\FrontEndApp\node_modules\wd\node_modules\request\request.js:1219:14)
    at Request.emit (events.js:164:20)
    at IncomingMessage.<anonymous> (C:\Users\User\Documents\mentrics\ODHWeb\FrontEndApp\node_modules\wd\node_modules\request\request.js:1167:12)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)`

**Comment by StasGrishaev** [comment]
неужели никто не сталкивался ? :) 
обидно работать без этого динозавра, там частенько вёрстка плывёт

**Comment by DudaGod** [comment]
Привет.

У тебя все тесты в IE11 с такой ошибкой падают? Можешь какой то minimal case написать, чтобы я у себя мог подебажить?

**Comment by StasGrishaev** [comment]
@DudaGod привет ! 
да, вообще все. интересует именно код сьюта ? если да, то вот пример : 

```
gemini.suite( "CatalogOfQuizzes page", function( suite ) {
	suite.setUrl( "/CatalogOfQuizzes" )
	     .before( function( actions ) {
		     actions.wait( 2000 );
	     } )
	     .setCaptureElements( [
		     ".Layout",
	     ] )
	     .capture('1080', function(actions) {
      		actions.setWindowSize(1920, 1080);
    	 })
    	 .capture('mobile', function(actions) {
      		actions.setWindowSize(375, 667);
    	 })
	     .capture('1024', function(actions) {
      		actions.setWindowSize(1280, 1024);
    	 }) 
} );
```

скриншот стека :
![image](https://user-images.githubusercontent.com/19959547/35571333-d9f52642-05e2-11e8-929d-b09c731faa53.png)

**Comment by DudaGod** [comment]
Мне нужен сайт на который я могу сходить из теста, например тот который ты тестируешь. Если ты сайт у тебя работает только локально на твоем компе, тогда пришли небольшой тест написанный для какого то популярного сайта. Например для `github.com`. Главное чтобы у тебя эта проблема воспроизвелась на нем.

**Comment by StasGrishaev** [comment]
@DudaGod провозился около часа с разными стендами и наконец то локализовал проблему. дело в ожидании появлении элемента в `before` блоке. прикладываю код для воспроизведения : 

`.gemini.js`:

```js
module.exports = {
    rootUrl: 'http://ya.ru',
    gridUrl: 'http://127.0.0.1:4444/wd/hub',
    compositeImage: true,
    sessionsPerBrowser: 1,
    calibrate: false,

    browsers: {
        // chrome: {
        //     screenshotsDir: './screens/chrome',
        //     windowSize: '1920x1080',
        //     desiredCapabilities: {
        //         browserName: 'chrome'
        //     }
        // },
        // firefox:{
        //     windowSize: '1920x1080',
        //     screenshotsDir: './screens/ff',
        //     desiredCapabilities:{
        //         browserName: 'firefox',
        //         marionette: false
        //     }
        // },
        // edge:{
        // 	windowSize: '1920x1080',
        //     screenshotsDir: './screens/edge',
        //     desiredCapabilities:{
        //         browserName: 'MicrosoftEdge'
        //     }
        // },
        ie:{
            windowSize: '1920x1080',
            screenshotsDir: './screens/ie11',
            desiredCapabilities:{
                browserName: 'internet explorer',
                version: '11'
            }
        }
    },

    sets:{
    	chrome:{
    		files:"C:/Users/User/Documents/myQuiz/tests"
    	},
    	// firefox:{
    	// 	files:"C:/Users/User/Documents/mentrics/ODHWeb/FrontEndApp/__test__/css_regression"
    	// },
    }
};
```
suite:

```js
gemini.suite( "Landing page", function( suite ) {
	suite.setUrl( "/" )
		 // .skip('edge')
	     .before( function( actions ) {
		     actions.waitForElementToShow( ".b-table.layout__table", 5000 );
	     } )
	     .setCaptureElements( [
		     ".b-table.layout__table",
	     ] )
	     .capture('1080', function(actions) {
      		actions.setWindowSize(1920, 1080);
    	 })
	     .capture('1024', function(actions) {
      		actions.setWindowSize(1280, 1024);
    	 })
    	 .capture('mobile', function(actions) {
      		actions.setWindowSize(375, 667);
    	 })
} );
```

в случае если меняем `actions.waitForElementToShow( ".b-table.layout__table", 5000 );` на `actions.wait( 2000 );` - всё работает как часы

**Comment by StasGrishaev** [comment]
@DudaGod попутно хочу задать вопрос по Edge ( 16.16299 ) браузеру - столкнулся с его ужасной работой при `compositeImage: true` - прикладываю пример - на нём заметно как криво склеивается страница ( элементы задваиваются ) при наличии вертикального скролла к ней. проблема самого браузера и его драйвера или всё же gemini ? 

![image](https://user-images.githubusercontent.com/19959547/35582191-1f536b38-05ff-11e8-84d0-257f1caef98f.png)

**Comment by j0tunn** [comment]
Есть не нулевая вероятность, что дело в верстке. Такое бывает когда на странице есть скрол и  фиксированные элементы (допустим что-то всегда центруется или лепится к низу): gemini отскринил, посмотрел, что блок не влез на 200 px, проскроллил ниже, блок переехал ниже, gemini отскринил, вырезал эти 200 px, и доклеил к оригинальному изображению.

**Comment by DudaGod** [comment]
с IE11 я сегодня подебажу, как освобожусь

**Comment by DudaGod** [comment]
Прости, завал на работе был, не успел подебажить.

Я попробовал сейчас запустить твой тест используя твой конфиг и такую же версию gemini. И у меня данная проблема не воспроизводится, все тесты проходят без проблем. 
Ты уверен, что у тебя последний предоставленный тобой тест не проходит только в IE? Судя по ошибке он почему то не может на странице найти элемент `.b-table.layout__table`.

**Comment by StasGrishaev** [comment]
@DudaGod привет, проблемы были исключительно в IE11. на данный момент временно отложил gemini в сторону из за занятости, но спасибо что посмотрел данный момент !

**Comment by qwerty2323** [comment]
Апну тему, у меня такая же проблема в IE11 в `"gemini": "5.7.2"`.
При попытке ожидать элемент, тесты падают с исключением.
```
 throw new Error("no value passed to Element constructor");
    ^

Error: no value passed to Element constructor
```
