### ISSUE TITLE
gemini error no config found

### ISSUE THREAD

**Issue by masteryoda2018** [gemini-testing/gemini#938]
\\Roaming\npm\node_modules\gemini\lib\config\config-reader.js:23
        throw new GeminiError('No config found');
        ^

GeminiError: No config found
    at getDefaultConfig (C:\Users\\\Roaming\npm\node_modules\gemini\lib\config\config-reader.js:23:15)
    at Object.exports.read (C:\Users\\\Roaming\npm\node_modules\gemini\lib\config\config-reader.js:10:28)
    at readConfig (C:\Users\\\Roaming\npm\node_modules\gemini\lib\config\index.js:61:31)
    at new Config (C:\Users\\\Roaming\npm\node_modules\gemini\lib\config\index.js:28:18)
    at new Gemini (C:\Users\\\Roaming\npm\node_modules\gemini\lib\gemini.js:43:23)
    at mkGemini (C:\Users\\\Roaming\npm\node_modules\gemini\lib\cli\index.js:96:20)
    at Object.exports.run (C:\Users\\\Roaming\npm\node_modules\gemini\lib\cli\index.js:23:20)
    at Object.<anonymous> (C:\Users\\\Roaming\npm\node_modules\gemini\bin\gemini:33:25)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by j0tunn** [comment]
@masteryoda2018 Can you provide a little bit more info?
- your config
- file tree
- gemini version

**Comment by masteryoda2018** [comment]
gemini version = 5.9.1
file tree = I am not sure what this means ???
config = I don't have any config file listed under the gemini folder. The config file does NOT exists.

**Comment by j0tunn** [comment]
> config = I don't have any config file listed under the gemini folder. The config file does NOT exists.

But this is exactly what gemini tolds you. There should be config file in the project directory.

**Comment by masteryoda2018** [comment]
When I run the command, ` gemini test`,  I am getting this error message,

![image](https://user-images.githubusercontent.com/44713122/48071347-ba830b00-e19f-11e8-84f8-3586105a0516.png)

**Comment by masteryoda2018** [comment]
Is there a troubleshooting guide I can follow?  Instructions on how to configure gemini visual regression step by step.

Thanks

**Comment by j0tunn** [comment]
What about README: https://github.com/gemini-testing/gemini#configuring ?

**Comment by masi** [comment]
> > config = I don't have any config file listed under the gemini folder. The config file does NOT exists.
> 
> But this is exactly what gemini tolds you. There should be config file in the project directory.
Sure, but printing the exception makes it looks like a software error. Instead a nice message like "Gemini could not found a configuration file in the current directory." would be much more helpful. It could even list all the names it is looking for.

Masi
