### ISSUE TITLE
CLI deprecation error don't output replacement options

### ISSUE THREAD

**Issue by wKich** [gemini-testing/gemini#956]
gemini version:

master

Command used to run:

```
npm gemini --debug
```

Actual behaviour:

```
/Users/kich/Work/skbkontur/retail-ui/node_modules/gemini/lib/cli/deprecations.js:33
            throw new GeminiError(
            ^

GeminiError: Option --debug is removed
    at /Users/kich/Work/skbkontur/retail-ui/node_modules/gemini/lib/cli/deprecations.js:33:19
    at /Users/kich/Work/skbkontur/retail-ui/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/Users/kich/Work/skbkontur/retail-ui/node_modules/lodash/lodash.js:3010:24)
    at /Users/kich/Work/skbkontur/retail-ui/node_modules/lodash/lodash.js:4894:18
    at Function.forEach (/Users/kich/Work/skbkontur/retail-ui/node_modules/lodash/lodash.js:9342:14)
```

Expected behaviour:

```
/Users/kich/Work/skbkontur/retail-ui/node_modules/gemini/lib/cli/deprecations.js:33
            throw new GeminiError(
            ^

GeminiError: Option --debug is removed. Instead use --system-debug=true
    at /Users/kich/Work/skbkontur/retail-ui/node_modules/gemini/lib/cli/deprecations.js:33:19
    at /Users/kich/Work/skbkontur/retail-ui/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/Users/kich/Work/skbkontur/retail-ui/node_modules/lodash/lodash.js:3010:24)
    at /Users/kich/Work/skbkontur/retail-ui/node_modules/lodash/lodash.js:4894:18
    at Function.forEach (/Users/kich/Work/skbkontur/retail-ui/node_modules/lodash/lodash.js:9342:14)
```

**Comment by sipayRT** [comment]
tnx, will be fixed
